### ISSUE TITLE
invalid SSL certificate

### ISSUE THREAD

**Issue by gmanchon** [lewagon/opengraph#4]
https://opengraph.lewagon.com/ does not have a valid SSL certificate, which prevents the tests of the `02-Data-Toolkit/02-Data-Sourcing/00-Warmup` data challenge from running correctly

In the meantime the tests have been changed in order to use a non secure URL in https://github.com/lewagon/data-solutions/pull/866

The instructions in the https://github.com/lewagon/opengraph#readme still reference the secure URL at the moment

**Comment by Eschults** [comment]
Thanks for reporting @gmanchon 🙏 

It looks like it was deployed w/ Heroku 👇 but I couldn't find it in Le Wagon's apps, maybe it was on your personal account @ssaunier?

<img width="687" alt="Screen Shot 2022-01-06 at 15 03 39" src="https://user-images.githubusercontent.com/8090140/148394872-9c29b92e-e66f-436f-9d83-b342a7c6e11f.png">

**Comment by ssaunier** [comment]
👋 I moved it to the `lewagon` account to get Paid Dynos => SSL certificate is back
